#%RAML 1.0 NamedExample
value:
  -
    transId: T1001
    transType: Debit
    accountNo: AC110
    amount: Rs. 1000.0
    transDate: December 28, 2021
    status: Debit successful
  -
    transId: T1002
    transType: Credit
    accountNo: AC101
    amount: Rs. 15000.0
    transDate: January 1, 2022
    status: Credit successful